spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
notification:
  mattermost:
    enabled: true # mmSender를 사용할 지 여부, false면 알림이 오지 않는다
    webhook-url: ${MM_WEBHOOK_URL} # 위의 Webhook URL을 기입
report:
  mattermost:
    enabled: true
    webhook-url: ${MM_REPORT_URL}
    pretext: 신고 누적 발생 알림!